#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
DOWNLOAD_URL_CHECKSUM=""
DOWNLOAD_URL_IMAGE="https://github.com/bigtreetech/CB2/releases/download/V1.0.5/CB2_Debian11_minimal_kernel4.19_20240619.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export MODULES="base,deb_namserver,passwordless_sudo,pkgupgrade(network,cb2config,klipper,node,is_req_preinstall,moonraker,cb2spi,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot_cb2),dfu-util),password-for-sudo),postrename"